### ISSUE TITLE
AddCounterコンポーネントについて

### ISSUE THREAD

**Issue by KoichiKiyokawa** [EyupTuncel/counter-project#1]
コンポーネント名が微妙です
ボタンを表すコンポーネントなのでCounterAddButtonとかでしょうか🤔

**Comment by KoichiKiyokawa** [comment]
また、ボタンの部分をコンポーネントにすることは間違いではないです
ただ、なぜコンポーネントにしたのか、考えを教えていただけると嬉しいです🙇‍♂️

**Comment by EyupTuncel** [comment]
実はそもそもカウンターにユニークなidを与えるためにこの関数を例のコンポーネントの中に入れていました。しかし、アプリのほうでは削除ボタンを押したら複数のカンターが一括に削除されるなどの不具合が生じました。その解決のためにApp.svelteに移動するなどしてコンポーネントをそのまま残しました。
function addNewCounter(e) {
    e.preventDefault();
    dispatch("addcounter", counter); 
    counter = {
      name: `Counter ${id + 1}`,
      value: 0,
      id: id + 1,
    };
  }

**Comment by KoichiKiyokawa** [comment]
そのコードだとidの重複が起きるので、複数のカウンターが消えたんだと思います。

このコンポーネントを作る理由の正解としては「scoped cssを使うため」などです。
まあ、とりあえずこのコンポーネントは残す方針で進めて大丈夫です 🙆‍♂️
