### ISSUE TITLE
mainタグの使い方を間違えている

### ISSUE THREAD

**Issue by KoichiKiyokawa** [EyupTuncel/counter-project#10]
https://github.com/EyupTuncel/counter-project/blob/3aa416aa240cececf289b7ed45acb427375c7ad8/src/components/Counter.svelte#L19

mainタグはhtml要素です
mdnのドキュメントなどで意味を調べてみましょう
コンポーネント全てで使うのは、たぶん間違いです

**Comment by EyupTuncel** [comment]
認識合わせのために伺いたいんですが、mainタグの使い方を間違えているとは
１．コンポーネントのsvelteファイルのテンプレート部分に何も書いてはいけません。
２．テンプレートの部分にbutton,div,p,h,inputなどのHTML要素を入れてもいいけど、<main></main>この二つを書いてその中に入れる必要はない。
上記のどれの意味でしょうか？

**Comment by KoichiKiyokawa** [comment]
今回の例で言うと、mainタグは1回だけApp.svelteで使うべきということです

**Comment by EyupTuncel** [comment]
”＜main＞ </main>” を削除しました。
