### ISSUE TITLE
型定義を書く

### ISSUE THREAD

**Issue by KoichiKiyokawa** [EyupTuncel/counter-project#18]
```ts
type Counter = { /* ... */ }
```
のように型定義を書いて、それを使ってみてください　（TypeScriptの練習のためです）

**Comment by EyupTuncel** [comment]
それぞれのタイプをconsole.log()で確認する練習をしました。

**Comment by KoichiKiyokawa** [comment]
TypeScriptのタイプはconsole.logでは確認することはできません
TypeScriptをコンパイルしてJavaScriptに変換するときに型定義は消えるからです。

**Comment by KoichiKiyokawa** [comment]
@EyupTuncel 
TypeScriptの型定義について、このページで確認してみてください
https://typescript-jp.gitbook.io/deep-dive/type-system

**Comment by EyupTuncel** [comment]
了解しました。
