### ISSUE TITLE
gokei

### ISSUE THREAD

**Issue by KoichiKiyokawa** [EyupTuncel/counter-project#4]
https://github.com/EyupTuncel/counter-project/blob/3aa416aa240cececf289b7ed45acb427375c7ad8/src/App.svelte#L14

英語の変数名にしましょう

ただし、英語だと難しい単語の場合は、母国語を変数名として使うのはOKだと僕は思っています🙆‍♂️

今回は簡単な単語なので英語が良いです

**Comment by EyupTuncel** [comment]
修正しました。
