### ISSUE TITLE
style属性に書くのをやめる

### ISSUE THREAD

**Issue by KoichiKiyokawa** [EyupTuncel/counter-project#5]
https://github.com/EyupTuncel/counter-project/blob/3aa416aa240cececf289b7ed45acb427375c7ad8/src/App.svelte#L35

このようにstyle=で書いてしまうと、CSSよりも優先されてしまい、制御が難しくなってしまいます。
CSSでスタイルを当てるようにしましょう

余裕があればtailwindcssというのを使うと良いです

**Comment by EyupTuncel** [comment]
修正しました。
