### ISSUE TITLE
変数宣言がおかしい

### ISSUE THREAD

**Issue by KoichiKiyokawa** [EyupTuncel/counter-project#7]
https://github.com/EyupTuncel/counter-project/blob/3aa416aa240cececf289b7ed45acb427375c7ad8/src/App.svelte#L6

ここはletを使うべきです
$との違いをもう一度確認すると良いです🙆‍♂️

**Comment by EyupTuncel** [comment]
今週と来週チュートリアルをもう一回読み直そうと思います。
ありがとうございます。
