### ISSUE TITLE
valueは避ける

### ISSUE THREAD

**Issue by KoichiKiyokawa** [EyupTuncel/counter-project#8]
https://github.com/EyupTuncel/counter-project/blob/3aa416aa240cececf289b7ed45acb427375c7ad8/src/App.svelte#L9

valueは意味が広すぎて、なんの値なのか伝わりません
countや、他の箇所で使ってるpointなど、具体的な名前にしましょう

**Comment by EyupTuncel** [comment]
承知しました。
