### ISSUE TITLE
100以上に増やせない

### ISSUE THREAD

**Issue by KoichiKiyokawa** [EyupTuncel/counter-project#9]
https://github.com/EyupTuncel/counter-project/blob/3aa416aa240cececf289b7ed45acb427375c7ad8/src/components/Counter.svelte#L11

こうした理由があれば、教えていただけると🙆‍♂️🙇‍♂️

**Comment by EyupTuncel** [comment]
勉強のために様々なことを試しているだけです。
上限があるときにどうすればいいのかなと考えてつけてみました。

**Comment by KoichiKiyokawa** [comment]
なるほど！
了解しました🙆‍♂️
